### ISSUE TITLE
Fonts not showing up correctly (system: The Dark Eye)

### ISSUE THREAD

**Issue by KnoepfchenFulla** [League-of-Foundry-Developers/fvtt-module-polyglot#177]
I'm trying to use Polyglot with my game system (The Dark Eye version 2.2.0), but fonts don't show up correctly.

In the Polyglot language setting, different fonts represent the world's different languages:
![2021-07-31_13-31-58](https://user-images.githubusercontent.com/79639045/127764029-3b9c86d8-7ab8-4308-9794-c0978e54b042.jpg)

But in the chat, all languages look like this on the GM's side:
![2021-07-31_23-37-58](https://user-images.githubusercontent.com/79639045/127764041-52d86726-6815-4e87-ae8c-73a4bfb882ed.jpg)

And like this on the players' side:
![2021-07-31_23-42-12](https://user-images.githubusercontent.com/79639045/127764048-5abfe784-a91b-48d3-b63c-b54f8ef01e6f.jpg)

Same for the journal entries (screenshot of the players' view):
![Sprachen2](https://user-images.githubusercontent.com/79639045/127764063-0ffe07d0-7f96-4d04-bd91-fe77c4a90180.jpg)

I noticed that on the GM's end, the chat will look exactly the same (using the generic scrambling seen in the journal screenshot above) as on the players' side until I open up the "language settings" under "module settings". Without changing anything in there, just by clicking "save", the font displayed on the GM's end changes to the default alphabet for all languages, while it stays generic on the players' end, also without distinguishing between what should be different scripts.

These are my module settings:
![2021-08-01_10-13-50](https://user-images.githubusercontent.com/79639045/127764247-f79f9b02-1396-4e2f-8c7c-55cab0dca756.jpg)

**Comment by mclemente** [comment]
This issue with the fonts not being shown correctly to the players was fixed, but I'm not sure if the rest of the issues were fixed since I couldn't replicate them.

**Comment by KnoepfchenFulla** [comment]
Yes, the same fonts now show up for both GM and players. But it's still the same (default) font for different scripts/alphabets. Whatever I set as the default here... 

![2021-08-01_12-23-16](https://user-images.githubusercontent.com/79639045/127767540-af04ae3f-d4ea-46f0-92df-38408eefe9c4.jpg)

...gets used for every alphabet it seems:

![2021-08-01_12-24-17](https://user-images.githubusercontent.com/79639045/127767555-4ae35c17-9776-4475-8f6c-7bafdebf2932.jpg)

The players' view reflects that (a reload on the players' side is necessary after the GM changed the default alphabet, but after that, it looks the same as it does for the GM). 

But while Zhayad should use Zhayad-Zeichen and Bosparano should use Kulsiker Zeichen, they both are displayed using whatever the default alphabet is.

Thank you for your help!

**Comment by mclemente** [comment]
The issue was similar to the Languages. Tell me if it's fixed now.

**Comment by KnoepfchenFulla** [comment]
It doesn't look like anything changed I'm afraid.

**Comment by ShahynRox** [comment]
System: Polyglot module 1.7.7. Foundry 0.8.8. German
Same with me. No matter which language/font I choose, it is always the "default alphabet"-font that shows up in the chat window. I did not change anything in the module settings and let the default language option blank.
After that I checked the "Replace System's Languages" in the module settings, but this had no effect.
I also tried to change Foundry language to English but this caused the language dropdown-menu in the chat-window to disappear or stay empty.

**Comment by mclemente** [comment]
Hm, open the console (F12) and run this: `await game.settings.set("polyglot", "Languages", polyglot.polyglot.LanguageProvider.originalTongues);` (then Refresh the page if you have custom languages). It should reset the Languages setting.

> Same with me. No matter which language/font I choose, it is always the "default alphabet"-font that shows up in the chat window. I did not change anything in the module settings and let the default language option blank.

It will be blank because your characters had `Schrift (Name)` when it's looking for `Languages (Name)`.

**Comment by ShahynRox** [comment]
Hi. Thank you for your assistance! Sorry, the console command did not help. Still the same issue with the language display:

![Screenshot 1](https://user-images.githubusercontent.com/88293425/127825178-444e4405-4ddd-46e6-81ff-3954b37dedbc.jpg)

![Screenshot 2](https://user-images.githubusercontent.com/88293425/127825192-ac13c8a6-681b-4c81-b63e-55225891204c.jpg)

This is a chat screenshot from the GM's perspective:

![Screenshot 3](https://user-images.githubusercontent.com/88293425/127825200-5bdd56fe-9313-4659-9fba-fc7e4a8c1b59.jpg)

And the same chat from player's perspective (player speaks some of the languages used by GM):

![Screenshot 4](https://user-images.githubusercontent.com/88293425/127826344-2af0fc0b-37b4-4511-8ff3-9719a5118053.jpg)

Maybe this helps!

**Comment by mclemente** [comment]
Could any of you send me your worlds? I'm 100% missing something here, but debugging on your world will be way easier than trying to replicate it.

**Comment by ShahynRox** [comment]
Yes, here is a test-world I created for the polyglot-module:

[ForgeVTT-export-foundrypolyglottest-2021-08-03 v1.zip](https://github.com/League-of-Foundry-Developers/fvtt-module-polyglot/files/6923207/ForgeVTT-export-foundrypolyglottest-2021-08-03.v1.zip)

**Comment by KnoepfchenFulla** [comment]
I saw there was an update available and tested:

![2021-08-03_18-28-19](https://user-images.githubusercontent.com/79639045/128052284-ce1dcc30-ecb7-44e0-a36d-dbd4ee35c246.jpg)

I had to re-assign the alphabets to the languages, as everything was set to default in the settings, but now it seems to be working! :-)

**Comment by ShahynRox** [comment]
Great! Thank you so much for your effort! 
After running the console command and reassigning the standard language layout in the polyglot-settings now works fine! A few languages/scripts show strange signes (Goblinisch) and others still have the "default" font (Trollische Raumbildschrift/Hjaldingsche Runen): 
![Screenshot-5](https://user-images.githubusercontent.com/88293425/128174854-349bb65d-b331-4f0d-aac6-d35a537c899c.jpg)

**Comment by mclemente** [comment]
That's the default Goblin font, it's just that those characters are the numbers.
Try resetting the Language Settings, that should fix the fonts that still have the Ophidian characters.
